#!/bin/python3

import subprocess
import os
import socket


def update_workspaces(active):
    icons = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"]
    workspaces = icons

    widget = "(box :spacing 10 :space-evenly true "
    for i in range(0, 10):
        if i == active - 1 or (i == 9 and active == 0):
            button_active = "workspace_active"
        else:
            button_active = "workspace_inactive"

        button = '(button :class "{button_active}" :onclick "" "{icon}")'.format(
            button_active=button_active, icon=icons[i]
        )
        widget += " " + button

    widget += ")"
    subprocess.run(f"echo '{widget}'", shell=True)


hyprland_socket = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
hyprland_server = f'/tmp/hypr/{os.environ["HYPRLAND_INSTANCE_SIGNATURE"]}/.socket2.sock'
print(hyprland_server)
hyprland_socket.connect(hyprland_server)

update_workspaces(1)

while True:
    event = hyprland_socket.recv(4096).decode("utf-8")
    for item in event.split("\n"):
        if "workspace>>" == item[0:11]:
            update_workspaces(int(item[-1]))
